env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-essential
  - standard-with-typescript
  - '@vue/eslint-config-prettier'
overrides: []
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
  extraFileExtensions: ['.vue']
plugins:
  - vue
rules: {}
